### ISSUE TITLE
bgd is ignoring instances, memory and disk_quota from manifest.yml

### ISSUE THREAD

**Issue by rbprado** [bluemixgaragelondon/cf-blue-green-deploy#67]
Hi there!

I noticed that bgd is ignoring the instances, memory and disk_quota from the manifest.yml file.

My app is running on PCF currently with 3 Instances, 1G memory and 1G disk.
If I try to redeploy with bgd over this app the deploy do not scale with the new resources.

If there is no app running, the deploy uses the data from the manifest.yml creating a app with the right resources.

My manifest.yml file:
```
applications:
- buildpack: staticfile_buildpack
  disk_quota: 2G
  env:
    GRANT_TYPE: password
    RESOURCE_URL: https://test.com
    SKIP_SSL_VALIDATION: true
    SSO_AUTO_APROVED_SCOPES: open.id, todo.read
    SSO_IDENTITY_PROVIDERS: SSO
    SSO_REDIRECT_URIS: https://test.com/
    SSO_SCOPE: open.id, todo.read
  instances: 4
  memory: 2G
  name: app-devops
  random-route: false
  services:
  - config-server
```

Here the output from the command trying to redeploy the app:
```
# cf bgd app-name -f manifest.yml -smoke-test smoketest.sh
Deleting app app-name-old in org Org / space devops as devops...
OK
Using manifest file manifest.yml

Creating app app-name-new in org Org / space devops as devops...
OK

Using route app-name-new.test.com
Binding app-name-new.test.com to app-name-new...
OK

Uploading app-name-new...
Uploading app files from: /home/jenkins-slave/workspace/deploy-module
Uploading 477.6K, 66 files

                             
Done uploading
OK
Binding service sbil-config-server to app app-name-new in org Org / space devops as devops...
OK

Starting app app-name-new in org Org / space devops as devops...
Downloading staticfile_buildpack...
Downloaded staticfile_buildpack
Creating container
Successfully created container
Downloading app package...
Downloaded app package (7.2M)
-----> Staticfile Buildpack version 1.4.21
-----> Installing nginx
       Using nginx version 1.13.8
-----> Installing nginx 1.13.8
       Copy [/tmp/buildpacks/4797a036f87bb3928bb164c574a43e2d/dependencies/3292a1fdf05213ded5bd38c322c33b1c/nginx-1.13.8-linux-x64-9585c5f4.tgz]
-----> Root folder /tmp/app
-----> Copying project files into public
-----> Configuring nginx
Exit status 0
Uploading droplet, build artifacts cache...
Uploading build artifacts cache...
Uploading droplet...
Uploaded build artifacts cache (218B)
Uploaded droplet (9.9M)
Successfully destroyed container
Uploading complete
Stopping instance c5e39b2b-46b6-43a1-90ab-4bcddd71a514
Destroying container

3 of 3 instances running

App started


OK

App app-name-new was started using this command `$HOME/boot.sh`

Showing health and status for app app-name-new in org Org / space devops as devops...
OK

requested state: started
instances: 3/3
usage: 1G x 3 instances
urls: app-name-new.test.com
last uploaded: Fri May 4 20:26:59 UTC 2018
stack: cflinuxfs2
buildpack: staticfile_buildpack

     state     since                    cpu    memory    disk      details
#0   running   2018-05-04 03:27:25 PM   0.0%   0 of 1G   0 of 1G
#1   running   2018-05-04 03:27:26 PM   0.0%   0 of 1G   0 of 1G
#2   running   2018-05-04 03:27:25 PM   0.0%   0 of 1G   0 of 1G
ssh support is enabled for 'app-name'

ssh support is already enabled for 'app-name-new'

Removing route app-name-new.test.com from app app-name-new in org SvcsIT-AnEOrg / space devops as devops...
OK
Creating route app-name.test.com for org SvcsIT-AnEOrg / space devops as devops...
OK
Route app-name.test.com already exists
Adding route app-name.test.com to app app-name-new in org SvcsIT-AnEOrg / space devops as devops...
OK
Renaming app app-name to app-name-old in org SvcsIT-AnEOrg / space devops as devops...
OK
Renaming app app-name-new to app-name in org SvcsIT-AnEOrg / space devops as devops...
OK
Removing route app-name.test.com from app app-name-old in org SvcsIT-AnEOrg / space devops as devops...
OK
```
