### ISSUE TITLE
New app has unexpected url in environment variable

### ISSUE THREAD

**Issue by NickVanderPyle** [bluemixgaragelondon/cf-blue-green-deploy#73]
### Observed Error:
Environment variable `url` from (bluemix) IBM Cloud is suffixed with `-new` at the end of the subdomain.
Malformed subdomain is suffixed to a route that should have no subdomain.
Example from manifest below:

> a-mybluemix-app-new.a-system-domain.ibm.com

### Expected Result:
`url` environment variable should be the same as if the app were deployed normally with `cf push $CF_APP`. `-new` and `-old` should not be part of the url.

### How:
Using cf-blue-green-deploy from staging.
NodeJS app with `passport-idaas-openidconnect` and `express` dependencies.
Manifest.yml like:
```yaml
applications:
- name: a-mybluemix-app
  buildpack: sdk-for-nodejs
  command: node dist/app.js
  routes:
  - route: a-system-domain.ibm.com
  - route: a-mybluemix-app.mybluemix.net
```

### Workaround:
Custom deploy script where existing is renamed and new deploy isn't given an unexpected app name. Routing is taken from manifest.

```bash
trap reportError ERR
reportError() {
    set +e

    if cf app "${CF_APP}_OLD"; then
        cf delete $CF_APP -f
        cf rename "${CF_APP}_OLD" $CF_APP
    fi

    exit 1
}

if cf app $CF_APP; then
    cf rename $CF_APP "${CF_APP}_OLD"
fi

cf push $CF_APP
cf delete -f "${CF_APP}_OLD"
```
