### ISSUE TITLE
Can't push single app while specifying manifest

### ISSUE THREAD

**Issue by iKrushYou** [bluemixgaragelondon/cf-blue-green-deploy#85]
I am trying to push a single app at a time while specifying a manifest and I am getting an error that doesn't seem to be accurate:

```
C02X2PA8JG5H:armada akrush$ cf bgd armada-ui -f manifest-uat.yaml 
Using manifest file manifest-uat.yaml

Could not push new version - Incorrect Usage. Command line flags (except -f) cannot be applied when pushing multiple apps from a manifest file.
```

It looks like it thinks I'm trying to push multiple apps at the same time? Also, it's saying flags except `-f` can't be specified and i'm only using `-f`

**Comment by holly-cummins** [comment]
Could you share your manifest?

**Comment by iKrushYou** [comment]
```
---
applications:

- name: armada-gateway
  path: ../../armada-gateway/target/armada-gateway-1.0.0-RELEASE.jar
  buildpack: java_buildpack_offline
  routes:
  - route: armada.apps.pcf.devfg.rbc.com
  env:
    SPRING_PROFILES_ACTIVE: dev,cloud
    TZ: GMT
  services:
  - sso-service
  - vault-service

- name: armada-ui
  path: ../../armada-ui/build/
  buildpack: staticfile_buildpack
  routes:
  - route: armada-ui.apps.pcf.devfg.rbc.com

- name: armada-security
  path: ../../armada-security/target/armada-security-1.0.0-RELEASE-exec.jar
  buildpack: java_buildpack_offline
  routes:
  - route: armada-security.apps.pcf.devfg.rbc.com
  env:
    SPRING_PROFILES_ACTIVE: dev,cloud
    TZ: GMT
  services:
  - sso-service
  - vault-service

- name: armada-scanning
  path: armada-scanning/target/armada-scanning-1.0.0-RELEASE-exec.jar
  buildpack: java_buildpack_offline
  routes:
  - route: armada-scanning.apps.pcf.devfg.rbc.com
  env:
    SPRING_PROFILES_ACTIVE: dev,cloud
    TZ: GMT
  services:
  - sso-service
  - vault-service

- name: armada-cmdb
  path: armada-cmdb/target/armada-cmdb-1.0.0-RELEASE-exec.jar
  buildpack: java_buildpack_offline
  routes:
  - route: armada-cmdb.apps.pcf.devfg.rbc.com
  env:
    SPRING_PROFILES_ACTIVE: dev,cloud
    TZ: GMT
  services:
  - sso-service
  - vault-service

- name: armada-mission-control
  path: armada-mission-control/target/armada-mission-control-1.0.0-RELEASE-exec.jar
  buildpack: java_buildpack_offline
  routes:
  - route: armada-mission-control.apps.pcf.devfg.rbc.com
  env:
    SPRING_PROFILES_ACTIVE: dev,cloud
    TZ: GMT
  services:
  - sso-service
  - vault-service

- name: armada-virtualization
  path: armada-virtualization/target/armada-virtualization-1.0.0-RELEASE-exec.jar
  buildpack: java_buildpack_offline
  routes:
  - route: armada-virtualization.apps.pcf.devfg.rbc.com
  env:
    SPRING_PROFILES_ACTIVE: dev,cloud
    TZ: GMT
    JAVA_OPTS: -XX:MaxMetaspaceSize=300M
  services:
  - sso-service
  - vault-service
  memory: 2048M

- name: armada-population
  path: armada-population/target/armada-population-1.0.0-RELEASE-exec.jar
  buildpack: java_buildpack_offline
  routes:
  - route: armada-population.apps.pcf.devfg.rbc.com
  env:
    SPRING_PROFILES_ACTIVE: dev,cloud
    TZ: GMT
    JAVA_OPTS: -XX:MaxMetaspaceSize=300M
  services:
  - sso-service
  - vault-service
  memory: 3072M

- name: armada-provisioning
  path: armada-provisioning/target/armada-provisioning-1.0.0-RELEASE-exec.jar
  buildpack: java_buildpack_offline
  routes:
  - route: armada-provisioning.apps.pcf.devfg.rbc.com
  env:
    SPRING_PROFILES_ACTIVE: dev,cloud
    TZ: GMT
    JAVA_OPTS: -XX:MaxMetaspaceSize=300M
  services:
  - sso-service
  - vault-service
  memory: 2048M

- name: armada-vsight
  path: armada-vsight/target/armada-vsight-1.0.0-RELEASE-exec.jar
  buildpack: java_buildpack_offline
  routes:
  - route: armada-vsight.apps.pcf.devfg.rbc.com
  env:
    SPRING_PROFILES_ACTIVE: dev,cloud
    TZ: GMT
  services:
  - sso-service
  - vault-service

- name: armada-slack-bot
  path: slack-bot/target/slack-bot-1.0.0-RELEASE.jar
  buildpack: java_buildpack_offline
  routes:
  - route: armada-slack-bot.apps.pcf.devfg.rbc.com
  env:
    SPRING_PROFILES_ACTIVE: dev,cloud
    TZ: GMT




- name: armada-servernames
  path: armada-servernames/target/armada-servernames-1.0.0-exec.jar
  buildpack: java_buildpack_offline
  routes:
  - route: armada-servernames.apps.pcf.devfg.rbc.com
  env:
    SPRING_PROFILES_ACTIVE: dev,cloud
    TZ: GMT
  services:
    - sso-service
    - vault-service
```
