### ISSUE TITLE
Route map/unmap without host

### ISSUE THREAD

**Issue by gmllt** [bluemixgaragelondon/cf-blue-green-deploy#87]
CloudFoundry allows to map directly a domain to an application.

The cf-cli command `cf map-route my-application application.cloudfoundry.dev` is valid if the `application.cloudfoundry.dev` domain is created.

However, if the domain is created, the command `cf map-route my-application cloudfoundry.dev --hostname application` will fail as the route creation conflict with declared domain.

Manifest sample : 

```yaml
---
applications:
    -
        name: my-application
        routes:
            -
                route: application.cloudfoundry.dev
```

The plugin force the usage of `cf map-route my-application cloudfoundry.dev -n application` and fail at route creation.
Could it be interesting to try to execute the command `cf map-route my-application application.cloudfoundry.dev` after the first fail so it also try to map the route from a domain without host.

```go
func (p *BlueGreenDeploy) mapRoute(appName string, r plugin_models.GetApp_RouteSummary) {
	if _, err := p.Connection.CliCommand("map-route", appName, r.Domain.Name, "-n", r.Host); err != nil {
		if _, err := p.Connection.CliCommand("map-route", appName, r.Host+"."+r.Domain.Name); err != nil {
			p.ErrorFunc("Could not map route or domain", err)
		}
	}
}
```

(Same for the route unmapping)
